version: '3.8'

services:
  mysql:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: nest-events
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: dev
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql/data
    command: [--ignore-db-dir=lost+found]
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
    mysql-data:
