name: Make Envfile

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  make-envfile:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: dev
      - name: Make dev envfile
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_APP_URL: ${{ vars.APP_URL }}
          envkey_DB_DROP_SCHEMA: ${{ vars.DB_DROP_SCHEMA }}
          envkey_DB_HOST: ${{ vars.DB_HOST }}
          envkey_DB_PORT: ${{ vars.DB_PORT }}
          envkey_SUPPORT_EMAIL: ${{ vars.SUPPORT_EMAIL }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
          directory: ./
