name: Develop action

on:
  workflow_dispatch:
  push:
    branches: ['dev']

jobs:
  checkout:
    runs-on: [self-hosted, dev]

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
        run: pm2 restart dist\main.js --update-env
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          DB_NAME: ${{ secrets.DB_NAME }}
          APP_URL: ${{ vars.APP_URL }}
          DB_DROP_SCHEMA: ${{ vars.DB_DROP_SCHEMA }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          SUPPORT_EMAIL: ${{ vars.SUPPORT_EMAIL }}
